version: '2.18.1'
services:
  api:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__Server=localhost,1433;Database = Aeropuerto_DB;User Id=sa;Password=Aeropuerto.311;Encrypt=false;TrustServerCertificate=true

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Aeropuerto.311"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
